# Generated by Django 3.2.25 on 2025-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.TextField(null=True, verbose_name='name'),
        ),
    ]
