# Generated by Django 3.2.25 on 2024-07-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agreementsignature_contributor_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementsignature',
            options={'verbose_name': 'agreement_signature', 'verbose_name_plural': 'agreement_signatures'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
    ]
