# Generated by Django 3.2.25 on 2024-07-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240709_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
